apiVersion: v1
kind: Pod
metadata:
  name: sleep-pod
  labels:
    app: sleep-forever
spec:
  containers:
  - name: sleep-forever
    image: quay.io/bryonbaker/sleep-forever:v1.0.1
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
      seccompProfile:
        type: RuntimeDefault
  securityContext:
    runAsNonRoot: true
